[workspace]
members = [
    "crates/pdf",
    "crates/graphics_state",
    "crates/shared",
    "examples/pdf/playground",
]

exclude = [
    ".vscode/*",
    "examples/*",
]

resolver = "2"

# Uncomment this when profiling.
#[profile.release]
#debug = true
